#!/bin/sh

set -e
cd "${HOME}/home.d/"
test -e unix-home-dir-private/.git ||
    git clone https://github.com/rzjnzk/unix-home-dir-private
cd unix-home-dir-private
git pull origin master
git checkout master
sh repocr.sh encrypt
git add -A
git commit --edit --signoff --status --verbose
git push -f master origin
cd ../..
